version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: 'npm'
    directory: '/client'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - 'react*'
        update-types:
          - 'patch'
    ignore:
      - dependency-name: 'react*'
        update-types: 
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
      - dependency-name: '*'
        update-types: 
          - 'version-update:semver-major'
          - 'version-update:semver-patch'

  - package-ecosystem: 'docker'
    directory: '/client'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 3
    labels:
      - 'docker'
