version: 2
updates:
 - package-ecosystem: "npm"
   directory: "server"
   schedule:
     interval: "daily"
   groups:
    production-dependencies:
     dependency-type: "production"
    development-dependencies:
     dependency-type: "development"
