version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "server"
  #   schedule:
  #     interval: "daily"
  #   groups:
  #     production-dependencies:
  #       dependency-type: "production"
  #     development-dependencies:
  #       dependency-type: "development"
      

  - package-ecosystem: "npm"
    directory: "client"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      react:
        patterns:
          - 'react*'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
